OPENAI_API_KEY = "<open_ai_api_key>"
DB_CONN_STR = "<connection_string_for_couchbase_cluster>"
DB_USERNAME = "<username_for_couchbase_cluster>"
DB_PASSWORD = "<password_for_couchbase_cluster>"
DB_BUCKET = "<name_of_bucket_to_store_documents>"
DB_SCOPE = "<name_of_scope_to_store_documents>"
DB_COLLECTION = "<name_of_collection_to_store_documents>"
INDEX_NAME = "<name_of_fts_index_with_vector_support>"
EMBEDDING_MODEL = "text-embedding-3-small" # OpenAI embedding model to use to encode the documents
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com" # Langsmith API endpoint
LANGCHAIN_API_KEY = "<langsmith_api_key>"
AUTH_ENABLED = "False" # enables authentication for the streamlit app using LOGIN_PASSWORD
LOGIN_PASSWORD = "<password to access the streamlit app>"
